AttendanceApp/Controllers/MyAttendanceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendanceApp.DAL;
using AttendanceApp.Models;
using Newtonsoft.Json;
using PagedList;


namespace AttendanceApp.Controllers
{
    public class MyAttendanceController : Controller
    {
		// GET: MyAttendance


		private EmployeeDBContext db = new EmployeeDBContext();
	 
		public ActionResult Index()
        {

			Employee userinfo = JsonConvert.DeserializeObject<Employee>(User.Identity.Name);
			int userID = Int32.Parse(userinfo.ID.ToString());

			List<Attendance> attendanceList =  db.Attendance.ToList().Where(x => x.EmployeeID == userID ).ToList();

		

			return View(attendanceList);
        }

		public ActionResult All(int? page )
		{



			List<Employee> Employees = db.Employee.ToList();

			List<Attendance> attendanceList = db.Attendance.ToList();

		
			List<SelectListItem> listDD = new List<SelectListItem>();

			foreach(var e in Employees){
				listDD.Add(new SelectListItem
				{
					Value = e.ID.ToString(),
					Text = e.FirstName + e.LastName

				});

			}

			

			TempData["Employees"] = listDD;
			TempData["EmployeesNames"] = Employees;








			return View(attendanceList);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult All(int? Employee  , int? page, string start, string end)
		{
			

			List<Attendance> attendanceList;




			if (Employee != null)
			{

				if (start != "" && end != "")
				{


					DateTime dtstart = Convert.ToDateTime(start);
					DateTime dtend = Convert.ToDateTime(end);

					attendanceList = db.Attendance.ToList().Where(x => x.EmployeeID == Employee && x.DateOfDay >= dtstart && dtend >= x.DateOfDay).ToList();

				}
				else {

					attendanceList = db.Attendance.ToList().Where(x => x.EmployeeID == Employee).ToList();
				}
			
				//int userID = Int32.Parse(Employee);
			
			}
			else if (start != "" && end != "" && Employee == null)
			{

				DateTime dtstart = Convert.ToDateTime(start);
				DateTime dtend = Convert.ToDateTime(end);
				attendanceList = db.Attendance.ToList().Where(x => x.DateOfDay >= dtstart && dtend >= x.DateOfDay).ToList();

			}
			else {
				attendanceList = db.Attendance.ToList();
			}
		
			List<Employee> Employees = db.Employee.ToList();
			
			List<SelectListItem> listDD = new List<SelectListItem>();
			foreach (var e in Employees)
			{
				listDD.Add(new SelectListItem
				{
					Value = e.ID.ToString(),
					Text = e.FirstName +" "+ e.LastName

				});

			}
			TempData["Employees"] = listDD;
			TempData["EmployeesNames"] = Employees;
			TempData["Start"] = start;
			TempData["End"] = end;




			return View(attendanceList);
		}

			public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Attendance attendance = db.Attendance.Find(id);
			if (attendance == null)
			{
				return HttpNotFound();
			}
			return View(attendance);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Attendance attendance)
		{
			if (ModelState.IsValid)
			{
				db.Entry(attendance).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(attendance);
		}


		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Attendance Attendance = db.Attendance.Find(id);
			if (Attendance == null)
			{
				return HttpNotFound();
			}
			return View(Attendance);
		}

		// POST: Employees/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Attendance Attendance = db.Attendance.Find(id);
			db.Attendance.Remove(Attendance);
			db.SaveChanges();
			return RedirectToAction("All");
		}


        public ActionResult MyAttendance()
        {
            throw new NotImplementedException();
        }
    }
}

AttendanceApp/Views/MyAttendance/All.cshtml
@model IEnumerable<AttendanceApp.Models.Attendance>
@using AttendanceApp.Models;
@using AttendanceApp.DAL;
@using PagedList.Mvc;



@{
	ViewBag.Title = "All";

	List<Employee> Employees = TempData["Employees"] as List<Employee>;
	string startDate = TempData["Start"] as string;
	string endDate = TempData["end"] as string;
	



}

<h2>Attendance</h2>



@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="row">
		<div class="form-group">
			<div class="col-md-12">
				Select Employee
			</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group">

				<div class="col-md-3">
					@Html.DropDownList("Employee",
						(IEnumerable<SelectListItem>)TempData["Employees"],
						"All Employee",
						new { @class = "form-control", onchange = "this.form.submit();" })
				</div>
				<div class="col-md-3">
					<input id="start" name="start" class="form-control datapiker" placeholder="Start" value="@startDate" />
					
					</div>
				<div class="col-md-3">

					<input class="form-control datapiker"  id="end" name="end" placeholder="End" value="@endDate" />
				</div>

				<div class="col-md-3">

					<input type="submit" value="Search" class="btn btn-default" />
					</div>


				</div>
		</div>






			}




			<table class="table" style="margin-top:10px;">
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.ComingTime)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.DateOfDay)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.LeaveTime)
					</th>
					<th>
						Employee Name
						</th>
<th></th>
				</tr>

				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.ComingTime)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.DateOfDay)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.LeaveTime)
						</td>
						<td>
							@DispayEmployee(item.EmployeeID)

						</td>
						
						<td>
							

							@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
						
							@Html.ActionLink("Delete", "Delete", new { id = item.ID })
						</td>
					</tr>
				}

			</table>



@section Scripts
{
	<script type="text/javascript">
        $(function () {
            $(".datapiker").datetimepicker({
                format: 'd/m/Y'
            });
        });

	</script>
}

@helper  DispayEmployee(int userID){


List<Employee> Employees = TempData["EmployeesNames"] as List<Employee>;
string username = "";

foreach (var E in Employees)
{

	if (E.ID == userID)
	{
		username = E.FirstName + " " + E.LastName;

	}



}


<span>
	@username

</span>


}

AttendanceApp/Views/MyAttendance/Delete.cshtml
@model AttendanceApp.Models.Attendance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attendance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ComingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "MyAttendance")
        </div>
    }
</div>

AttendanceApp/Views/MyAttendance/Edit.cshtml
@model AttendanceApp.Models.Attendance

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ComingTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComingTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ComingTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeaveTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeaveTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeaveTime, "", new { @class = "text-danger" })
            </div>
        </div>

		@Html.Hidden("EmployeeID")


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendanceApp/Views/MyAttendance/Index.cshtml
@model IEnumerable<AttendanceApp.Models.Attendance>

@using Newtonsoft.Json;
@using AttendanceApp.Models;
@using System;
@using System.Globalization;



@{
	ViewBag.Title = "Index";
	Employee userinfo = JsonConvert.DeserializeObject<Employee>(User.Identity.Name);
}

<h2>My Attendance</h2>


<table class="table">
    <tr>
       

		<th>
			@Html.DisplayNameFor(model => model.DateOfDay)
		</th>

        <th>
            @Html.DisplayNameFor(model => model.ComingTime)
        </th>
     
        <th>
            @Html.DisplayNameFor(model => model.LeaveTime)
        </th>
		@{
			if (userinfo != null)
			{


				if (userinfo.UserRoles == "Admin")
				{
					<th></th>

				}


			}
		}

        
    </tr>

@foreach (var item in Model) {
    <tr>
        
		<td>
			@Html.DisplayFor(modelItem => item.DateOfDay)
		</td>

        <td>
			@item.ComingTime



        </td>
    
        <td>
			@item.LeaveTime

	
        </td>


		@{
			if (userinfo != null)
			{


				if (userinfo.UserRoles == "Admin")
				{
					<td>
						@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |

						@Html.ActionLink("Delete", "Delete", new { id = item.ID })
					</td>

				}


			}
		}

       
    </tr>
}

</table>



@helper DisplayTime(string time)
{



DateTime dt = Convert.ToDateTime(time);


	<span>
		@dt.TimeOfDay.ToString()

	</span>


}